name: ci

on:
  push:
    branches:
      - feature/auto
  schedule:
    - cron: "* 3 * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Auto green
        run: |
          git config --local user.email "android@townwang.com"
          git config --local user.name "Townwang"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "Keep writing documents now..."
          git push
